#!/bin/sh

ECLIPSE_PLUGINS_DIR=/usr/share/eclipse4/plugins

JAR_BUNDLES=`ls $ECLIPSE_PLUGINS_DIR/*.jar | xargs -i basename {} .jar | sort | uniq`
DIR_BUNDLES=`ls -d $ECLIPSE_PLUGINS_DIR/*/ | xargs -i basename {} | sort | uniq`

BUNDLES_TO_START="org.eclipse.core.runtime org.eclipse.equinox.common org.eclipse.equinox.ds org.eclipse.equinox.event org.eclipse.equinox.simpleconfigurator"

bundle_start_str() {
  for bundle in $BUNDLES_TO_START; do
    [ "$bundle" = "$1" ] && echo "true" && return 0
  done
  echo "false"
}

(
	echo "#encoding=UTF-8"
	echo "#version=1"

	for bundle in $JAR_BUNDLES; do
		SYMBOLICNAME=$(echo $bundle | cut -f1 -d_)
		VERSION=$(echo $bundle | cut -f2 -d_)

		echo $SYMBOLICNAME,$VERSION,plugins/$bundle.jar,4,`bundle_start_str $SYMBOLICNAME`
	done

	for bundle in $DIR_BUNDLES; do
		SYMBOLICNAME=$(echo $bundle | cut -f1 -d_)
		VERSION=$(echo $bundle | cut -f2 -d_)

		echo $SYMBOLICNAME,$VERSION,plugins/$bundle,4,false
	done
) > /var/lib/eclipse4-platform/bundles.info

# Generate config.ini

OSGI_BUNDLE=$(basename $(ls $ECLIPSE_PLUGINS_DIR/org.eclipse.osgi_*.jar));
SIMPLECONFIGURATOR_BUNDLE=$(basename $(ls $ECLIPSE_PLUGINS_DIR/org.eclipse.equinox.simpleconfigurator_*.jar));
OSGI_COMPATIBILITY_STATE_BUNDLE=$(basename $(ls $ECLIPSE_PLUGINS_DIR/org.eclipse.osgi_*.jar));

echo "org.eclipse.update.reconcile=false
eclipse.p2.profile=epp.package.testing
osgi.instance.area.default=@user.home/workspace
osgi.framework=file\:plugins/$OSGI_BUNDLE
equinox.use.ds=true
eclipse.buildId=debian
osgi.bundles=reference\:file\:$SIMPLECONFIGURATOR_BUNDLE@1\:start
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
eclipse.product=org.eclipse.platform.ide
osgi.splashPath=platform\:/base/plugins/org.eclipse.platform
osgi.framework.extensions=reference\:file\:$OSGI_COMPATIBILITY_STATE_BUNDLE
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.p2.data.area=@config.dir/../p2
osgi.bundles.defaultStartLevel=4
" > /var/lib/eclipse4-platform/config.ini

exit 0
